name: cbg_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  http: ^1.2.1

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  month_picker_dialog: ^4.0.0
  fl_chart: ^0.70.0
  linked_scroll_controller: ^0.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image.png
    - assets/Logo.png
    - assets/company.png
    - .env